### ISSUE TITLE
.env.example file

### ISSUE THREAD

**Issue by mhbw** [TwilioDevEd/automated-survey-flask#6]
you mention the .env.example file but there isn't one here.  it exists in ivr-recording-laravel but not in this file. this documentation isn't clear; are we supposed to use that file from another project or make our own or... ?

**Comment by joliveros** [comment]
@mhbw,

Sorry for the confusion. This has been resolved with this [commit](https://github.com/TwilioDevEd/automated-survey-flask/commit/6e0bc1198aa8e2500d798b8948bb928d03ecdbb4).

Best regards,

José
