### ISSUE TITLE
manage.py failing

### ISSUE THREAD

**Issue by mhbw** [TwilioDevEd/automated-survey-flask#7]
running 

python manage.py dbseed

gets the error

Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from flask.flask_script import Manager
ImportError: No module named flask_script

**Comment by mhbw** [comment]
modifiying 

from flask.ext.script import Manager
from flask.ext.migrate import Migrate, MigrateCommand

to 

from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand

seem to succeed in fixing the issue

**Comment by joliveros** [comment]
Hi @mhbw, 

I was unable to reproduce the issue with python `2.7.13` or `3.4.6`. I would recommend perhaps installing either of those [versions](https://github.com/pyenv/pyenv-virtualenv) in a fresh virtual environment and following the steps in the readme again.

If you have any other issues I'll be happy to assist.

José
